
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_business_intelligence'
version: '1.3.0'
config-version: 2

require-dbt-version: ">=1.3.0"

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_business_intelligence'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  dbt_metrics_calendar_model: dim_date
  dbt_constraints_enabled: false
  company_name: 'Bigstore Enterprises'
  company_start_date: '2019-01-01'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_business_intelligence:
    # Config indicated by + and applies to all files under models/example/
    +materialized: table
    staging:
      +schema: staging
      +materialized: view
    metrics:
      +enabled: "{{ false if target.type == 'sqlserver' else true }}" # sqlserver does not allow nested CTE's, which metrics require
  metrics:
    dbt_metrics_default_calendar:
      +schema: staging
      +enabled: false
  elementary:
    +schema: 'elementary'

tests:
  +severity: warn  # all tests

seeds:
  dbt_business_intelligence:
    schema: staging # all seeds in this project will use the mapping schema by default
