name: Run File Generator and Download TDS File
on:
  repository_dispatch:
    types: [job.run.completed]
jobs:
  run-file-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Webhook Signature
        id: validate_signature
        run: |
          echo "Validating webhook..."
          # Extract the authorization header from GitHub event
          AUTH_HEADER="${{ github.event.headers.authorization }}"
          SECRET_TOKEN="${{ secrets.DBT_CLOUD_AUTH_TOKEN }}"
          # Get the raw request body
          REQUEST_BODY=$(jq -c . < $GITHUB_EVENT_PATH)

          # Calculate the HMAC SHA256 hash of the request body using the secret token
          EXPECTED_SIGNATURE=$(echo -n "$REQUEST_BODY" | openssl dgst -sha256 -hmac "$SECRET_TOKEN" | sed 's/^.* //')

          # Check if the authorization header matches the expected signature
          if [[ "$EXPECTED_SIGNATURE" != "$AUTH_HEADER" ]]; then
            echo "Webhook validation failed! Exiting."
            exit 1
          fi
          echo "Webhook validated successfully!"
      - name: Run file generator
        run: |
          mkdir -p output && \
          ./file_generator_linux \
          -H ${{ secrets.REDSHIFT_HOST_URL }} \
          -d redshift \
          -a password \
          -D dev \
          -P 5439 \
          -l LOCAL \
          -M "dim_customer, dim_date, dim_order, dim_product, fact_sales" \
          -A ${{ github.event.accountId }} \
          -j ${{ github.event.data.jobId }} \
          -T ${{ secrets.DBT_TOKEN }} \
          -s "./output/sales.tds"
      - name: Upload generated artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated-files
          path: ./output/
  download-artifacts:
    runs-on: ubuntu-latest
    needs: run-file-generator
    steps:
      - name: Download generated artifacts
        uses: actions/download-artifact@v3
        with:
          name: generated-files
          path: ./downloaded_files/
      - name: List downloaded files
        run: ls ./downloaded_files
