version: 2

models:
  - name: fact_sales
    description: "{{ doc('fact_sales') }}"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_key
            - order_key
            - product_key
            - date_key
    meta:
      label: Sales Fact
      display_index: 1
      # columns.tests.relationships will override meta.joins, but tests are not available in the cloud Metadata API
      joins:
        - to: dim_customer
          type: inner #inner, left, right, full; default 'inner'
          join_on:
            - from_field: customer_key
              exp: '=' #optional; default '='; '=','<>'
              to_field: customer_key
        - to: dim_order
          type: inner
          join_on:
            - from_field: order_key
              to_field: order_key
        - to: dim_product
          type: inner
          join_on:
            - from_field: product_key
              to_field: product_key
        - to: dim_date
          type: inner
          join_on:
            - from_field: date_key
              to_field: date_key
    columns:
      - name: customer_key
        meta:
          hidden: true
        tests:
          - not_null
          - relationships: #JOINS the dbt integrity way
              to: ref('dim_customer')
              field: customer_key
      - name: order_key
        meta:
          hidden: true
        tests:
          - not_null
          - relationships:
              to: ref('dim_order')
              field: order_key
      - name: product_key
        meta:
          hidden: true
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: date_key
        meta:
          hidden: true
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: date_day
        meta:
          hidden: true

  - name: dim_customer
    description: "{{ doc('dim_customer') }}"
    meta:
      label: Customer
      display_index: 4
    columns:
      - name: customer_key
        meta:
          label: customer_key
          hidden: true
        tests:
          - unique
      - name: customer_code
        meta:
          label: Customer Id
      - name: customer_name
        meta:
          label: Customer Name
          synonyms: # for business searching and natural language processing
            - Customer
            - Who
      - name: address
        meta:
          label: Address
      - name: postal_code
        meta:
          label: Postal Code
      - name: country
        meta:
          label: Country
      - name: latitude
        meta:
          label: Latitude
      - name: longitude
        meta:
          label: Longitude
      - name: contact_name
        meta:
          label: Contact Name
      - name: phone
        meta:
          label: Phone
      - name: email
        meta:
          label: Email

  - name: dim_order
    description: "{{ doc('dim_order') }}"
    meta:
      label: Order
      display_index: 2
    columns:
      - name: order_key
        meta:
          label: order_key
          hidden: true
        tests:
          - unique
      - name: order_number
        meta:
          label: Order Number
      - name: order_line_number
        meta:
          label: Order Line Number
      - name: order_date
        description: "Date of the order after {{ var('company_name') }} started on {{ var('company_start_date') }}"
        meta:
          label: Order Date
      - name: status
        description: "Status can be one of the following values: 'Cancelled', 'Delivered', 'Shipped'"
        meta:
          label: Order Status
        tests:
          - accepted_values:
              values: ['Cancelled','Delivered','Shipped']

  - name: dim_product
    description: "{{ doc('dim_product') }}"
    meta:
      label: Product
      display_index: 3
    columns:
      - name: product_key
        meta:
          hidden: true
        tests:
          - unique
      - name: product_code
        meta:
          label: Product Code
      - name: product_name
        meta:
          label: Product Name
          synonyms: # for business searching and natural language processing
            - Product
            - What
      - name: product_category
        meta:
          label: Product Category
          synonyms: # for business searching and natural language processing
            - Product Type
            - Product Line
      - name: msrp
        meta:
          label: MSRP
          format:
            type: number
            decimalPlaces: 2
            prefix: "$"
      - name: recent_order_date
        meta:
          label: Recent Order Date
      - name: first_order_date
        meta:
          label: First Order Date

  - name: dim_date
    description: The Order Date dimension allows you to analyze metrics across time periods at many levels of granularity (year, quarter, month, day).
    meta:
      label: Order Date
      display_index: 5
    columns:
      - name: date_key
        meta:
          label: date_key
          hidden: true
        tests:
          - unique
      - name: date_day
        meta:
          label: Order Date
          display_index: 1
      - name: prior_date_day
        meta:
          label: Prior Date Day
          hidden: true
          format:
            type: date
            pattern: 'MMM D, YYYY'
      - name: next_date_day
        meta:
          hidden: true
          label: Next Date Day
      - name: prior_year_date_day
        meta:
          hidden: true
          label: Prior Year Date Day
          grain: off # time interval grain; values 'off', 'day', 'week', 'month', 'quarter', 'year'
      - name: prior_year_over_year_date_day
        meta:
          hidden: true
          label: Prior Year Over Year Date Day
      - name: day_of_week
        meta:
          hidden: true
          label: Day Of Week
      - name: day_of_week_iso
        meta:
          hidden: true
          label: Day Of Week Iso
      - name: day_of_week_name
        meta:
          hidden: true
          label: Day Of Week Name
      - name: day_of_week_name_short
        meta:
          hidden: true
          label: Day Of Week Name Short
      - name: day_of_month
        meta:
          label: Day Of Month
      - name: day_of_year
        meta:
          label: Day Of Year
      - name: date_week # week_start_date
        meta:
          label: Week Start Date
          grain: off
      - name: week_end_date
        meta:
          hidden: true
          label: Week End Date
      - name: prior_year_week_start_date
        meta:
          hidden: true
          label: Prior Year Week Start Date
      - name: prior_year_week_end_date
        meta:
          hidden: true
          label: Prior Year Week End Date
      - name: week_of_year
        meta:
          hidden: true
          label: Week Of Year
      - name: iso_week_start_date
        meta:
          hidden: true
          label: Iso Week Start Date
      - name: iso_week_end_date
        meta:
          hidden: true
          label: Iso Week End Date
      - name: prior_year_iso_week_start_date
        meta:
          hidden: true
          label: Prior Year Iso Week Start Date
      - name: prior_year_iso_week_end_date
        meta:
          hidden: true
          label: Prior Year Iso Week End Date
      - name: iso_week_of_year
        meta:
          hidden: true
          label: Iso Week Of Year
      - name: prior_year_week_of_year
        meta:
          hidden: true
          label: Prior Year Week Of Year
      - name: prior_year_iso_week_of_year
        meta:
          hidden: true
          label: Prior Year Iso Week Of Year
      - name: month_of_year
        meta:
          label: Month Num
      - name: month_name
        meta:
          label: Month Name
      - name: month_name_short
        meta:
          label: Month Name Short
      - name: date_month # month_start_date
        meta:
          label: Month Start Date
          grain: off
      - name: month_end_date
        meta:
          hidden: true
          label: Month End Date
      - name: prior_year_month_start_date
        meta:
          hidden: true
          label: Prior Year Month Start Date
      - name: prior_year_month_end_date
        meta:
          hidden: true
          label: Prior Year Month End Date
      - name: quarter_of_year
        meta:
          label: Quarter Num
      - name: date_quarter # quarter_start_date
        meta:
          label: Quarter Start Date
          grain: off
      - name: quarter_end_date
        meta:
          hidden: true
          label: Quarter End Date
      - name: year_number
        meta:
          label: Year Num
          display_index: 2
      - name: date_year # year_start_date
        meta:
          label: Year Start Date
          grain: off
      - name: year_end_date
        meta:
          hidden: true
          label: Year End Date

  - name: product_monthly
    description: "{{ doc('product_monthly') }}"
    meta:
      label: Product Monthly
      hidden: true
    columns:
      - name: PRODUCT_CATEGORY
        description: ''
        meta:
          label: Product Category
      - name: PRODUCT_NAME
        description: ''
        meta:
          label: Product Name
      - name: PERIOD
        description: ''
        meta:
          label: Period
      - name: PRODUCT_KEY
        description: ''
        meta:
          hidden: true
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
      - name: SALES
        description: ''
        meta:
          label: Sales
      - name: RATIO_TO_1_MONTH_AGO
        description: ''
        meta:
          label: Ratio To 1 Month Ago
      - name: DIFFERENCE_TO_1_MONTH_AGO
        description: ''
        meta:
          label: Difference To 1 Month Ago
      - name: AVERAGE_FOR_MONTH
        description: ''
        meta:
          label: Average For Month
      - name: SUM_FOR_YEAR
        description: ''
        meta:
          label: Sum For Year
      - name: ROLLING_AVERAGE_6_MONTH
        description: ''
        meta:
          label: Rolling Average 6 Month
      - name: ROLLING_MIN_6_MONTH
        description: ''
        meta:
          label: Rolling Min 6 Month

  - name: stg_customer
    meta:
      hidden: true

  - name: stg_order
    meta:
      hidden: true

  - name: stg_product
    meta:
      hidden: true

  - name: stg_date_dimension
    meta:
      hidden: true

  - name: stg_sales_data
    meta:
      hidden: true
      # these joins are only to demonstrate the possibilities; the stg models will be hidden in BI tool;
      joins:
        - to: stg_customer
          type: left #inner, left, right, full
          join_on: #allows for multiple columns
            - from_field: customer_name
              exp: '=' #optional; default '='; '=','<>'
              to_field: customer_name
            - to_field: phone
              exp: '='
              from_field: 'phone'
              operator: OR #optional; default 'AND'; 'AND', 'OR' 'NOT'; TODO: grouping
        - to: stg_order
          type: right
          join_on:
            - from_field: order_number
              exp: '='
              to_field: order_number
            - to_field: order_line_number
              exp: '='
              from_field: order_line_number
              operator: AND
        - to: stg_product
          type: inner
          join_on:
            - from_field: product_code
              exp: '='
              to_field: product_code
        - to: stg_date_dimension
          type: full
          join_on:
            - from_field: order_date
              exp: '='
              to_field: date_day

metrics:
  - name: quantity
    label: Quantity
    model: ref('fact_sales')
    description: "Sum of quantity sold"
    calculation_method: sum
    expression: quantity
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key

  - name: price
    label: Price
    model: ref('fact_sales')
    description: "Average price"
    calculation_method: average
    expression: price
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key

  - name: sales
    label: Sales
    model: ref('fact_sales')
    description: "Sum of total sales revenue"
    calculation_method: sum
    expression: sales
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key
    meta:
      synonyms: # for business searching and natural language processing
        - Revenue
        - Proceeds
        - Receipts

  - name: target
    label: Target
    model: ref('fact_sales')
    description: "Sum of target sales revenue"
    calculation_method: sum
    expression: target
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key

  - name: row_count
    label: Row Count
    model: ref('fact_sales')
    description: "A non-distinct count of rows"
    calculation_method: count
    expression: order_key
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key

  - name: customer_count
    label: Customer Count
    model: ref('fact_sales')
    description: "A `distinct_count` of customers"
    calculation_method: count_distinct
    expression: customer_key
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key

  - name: product_count
    label: Product Count
    model: ref('fact_sales')
    description: "A `distinct_count` of products"
    calculation_method: count_distinct
    expression: product_key
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key

  - name: order_count
    label: Order Count
    model: ref('fact_sales')
    description: "A `distinct_count` of orders"
    calculation_method: count_distinct
    expression: order_key
    timestamp: date_day
    time_grains: [day, week, month, year]
    dimensions:
      - order_key
      - customer_key
      - product_key

sources:
  - name: salesforce
    # database: dbname/project, uses project database if not specified
    schema: "{{ target.schema }}_staging"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: data_loaded_at
    description: Data loaded from source systems
    tables:
      - name: stg_sales_data
        description: 'Sales data from the master system'
