sources:
  - name: salesforce
    # database: dbname/project, uses project database if not specified
    schema: "{{ target.schema }}_staging"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: data_loaded_at
    description: Data loaded from source systems
    tables:
      - name: stg_sales_data
        description: 'Sales data from the master system'