sources:
  - name: salesforce
    # database: dbname/project, uses project database if not specified
    schema: "{{ target.schema }}_raw"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: data_loaded_at
    description: Data loaded from source systems
    tables:
      - name: sales_data_raw
        description: 'Sales data from the master system'
        # to use parquet files as sources instead of seeded files for duckdb,
        # uncomment the following line and update the path
        # to the absolute path of the parquet file
        meta:
          external_location: '/db/raw/sales_data_raw.parquet'
      - name: order_data_raw
        description: 'Order data from the master system'
        # to use parquet files as sources instead of seeded files for duckdb,
        # uncomment the following line and update the path
        # to the absolute path of the parquet file
        meta:
          external_location: '/db/raw/order_data_raw.parquet'
      - name: product_data_raw
        description: 'Product data from the master system'
        # to use parquet files as sources instead of seeded files for duckdb,
        # uncomment the following line and update the path
        # to the absolute path of the parquet file
        meta:
          external_location: '/db/raw/product_data_raw.parquet'
      - name: customer_data_raw
        description: 'Customer data from the master system'
        # to use parquet files as sources instead of seeded files for duckdb,
        # uncomment the following line and update the path
        # to the absolute path of the parquet file
        meta:
          external_location: '/db/raw/customer_data_raw.parquet'
