sources:
  - name: salesforce
    # database: dbname/project, uses project database if not specified
    schema: "{{ target.schema }}_staging"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: data_loaded_at
    description: Data loaded from source systems
    tables:
      - name: sales_data_raw
        description: 'Sales data from the master system'
      - name: order_data_raw
        description: 'Order data from the master system'
      - name: product_data_raw
        description: 'Product data from the master system'
      - name: customer_data_raw
        description: 'Customer data from the master system'
