sources:
  - name: salesforce
    # database: dbname/project, uses project database if not specified
    schema: "raw"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: data_loaded_at
    description: Data loaded from source systems
    tables:
      - name: customer
        description: 'Customer data from the master system'
      - name: order
        description: 'Order data from the master system'
      - name: product
        description: 'Product data from the master system'
      - name: sales
        description: 'Sales data from the master system'
